### ISSUE TITLE
cara set status code

### ISSUE THREAD

**Issue by redikawest** [globalxtreme/response#7]
ini cara set response status code error gimana ya ?
misal data not found jadi 404, unauthorized 401, forbidden 403 dll

dari yang aku coba, kalau error status code nya cuma bisa 500 doang

**Comment by yuswa-arba** [comment]
Contoh error 404 & 403

if (!function_exists("errNotFound")) {
    function errNotFound($internalMsg = "", $status = 404)
    {
        error(Error::DEFAULT, $internalMsg, $status);
    }
}

if (!function_exists("errForbiden")) {
    function errForbiden($internalMsg = "", $status = 403)
    {
        error(Error::DEFAULT, $internalMsg, $status);
    }
}

**Comment by yuswa-arba** [comment]
coba buka di
https://github.com/globalxtreme/response/blob/master/src/Misc/responses.php

di situ ada contohnya
